# Paths for data storage
data_paths:
  raw_data: "data/raw"
  processed_data: "data/processed"

# Model parameters
model_params:
  model_name: "facebook/wav2vec2-large-xlsr-53"
  fine_tune_epochs: 3
  learning_rate: 5e-5

# Logging configurations
logging:
  level: "INFO"
  log_file: "logs/training_log.txt"